# This workflow runs continuous integration checks on push to master
name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.29.3
        cache: true

    - name: Cache Flutter dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          ${{ runner.tool_cache }}/flutter
        key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Cache Ubuntu packages
      uses: actions/cache@v4
      with:
        path: |
          /var/cache/apt
          /var/lib/apt
        key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/*.yml') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Get media_kit libs
      run: |
        sudo apt-get update
        sudo apt-get install libmpv-dev -y

    - name: Get dependencies
      run: flutter pub get

    - name: Verify formatting
      run: dart format --output=none --set-exit-if-changed .

    - name: Analyze project source
      run: flutter analyze --fatal-infos --fatal-warnings

    - name: Check for outdated dependencies
      run: flutter pub deps

  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    needs: analyze
    steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.29.3
        cache: true

    - name: Cache Flutter dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          ${{ runner.tool_cache }}/flutter
        key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Cache Ubuntu packages
      uses: actions/cache@v4
      with:
        path: |
          /var/cache/apt
          /var/lib/apt
        key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/*.yml') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Get media_kit libs
      run: |
        sudo apt-get update
        sudo apt-get install libmpv-dev -y

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK (Debug)
      run: flutter build apk --debug

    - name: Build APK (Release)
      run: flutter build apk --release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apk-builds
        path: build/app/outputs/apk/**/*.apk
        retention-days: 7
