# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.29.3
        
    - name: Get media_kit libs
      run: |
        apt-get update
        apt-get install libmpv-dev -y
  
    - run: flutter --version
    - run: flutter pub get
    - run: flutter pub deps
    - run: flutter test
    - run: flutter build apk --debug --split-per-abi
    
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.TOKEN }}
        prerelease: true
